import {StyleSheet, Dimensions} from 'react-native';
const {width, height} = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    width,
    height,
    position: 'relative',
    backgroundColor: 'pink',
  },
  wrapper: {
    position: 'absolute',
    left: '0%',
    right: '0%',
    top: '-0.23%',
    bottom: '0%',
    backgroundColor: '#F5F5F5',
    marginTop: 15,
  },
  upperCont: {
    position: 'absolute',
    left: '0%',
    right: '0%',
    top: '-6.89%',
    bottom: '80.77%',
    borderRadius: 50,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  upperWrapper: {
    width: '100%',
    height: height * 0.22,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  backIconWrapper: {
    width: width * 0.2,
    height: height * 0.05,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  uName: {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: width * 0.047,
    lineHeight: 25,
    color: '#fff',
    marginRight: 50,
  },
  dropdownWrapper: {
    width: width * 0.27,
    height: height * 0.04,
    backgroundColor: '#fff',
    borderRadius: 25,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'rgba(255, 255, 255, 255)',
    elevation: 1,
    marginRight: 15,
  },
  dropdownSelectedText: {
    padding: 5,
    color: 'rgb(85,136,231)',
    fontSize: width * 0.034,
  },
  dropdownImg: {
    width: width * 0.034,
    height: height * 0.011,
  },
  cardWrapper: {
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    position: 'absolute',
    left: '5.75%',
    right: '5.75%',
    top: '10.22%',
    bottom: '20.83%',
    backgroundColor: '#ffffff',
    shadowColor: 'rgba(0, 0, 0, 0.25)',
    borderRadius: 20,
    elevation: 1,
  },
  docSpecsWrapper: {
    width: '95%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
    paddingLeft: 45,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#ECECEC',
  },
  docNameSpecsText: {
    display: 'flex',
    flexDirection: 'column',
  },
  docNameText: {
    color: '#000',
    fontSize: width * 0.04,
    fontWeight: 'bold',
    paddingBottom: 5,
    marginLeft: 5,
  },
  docSubNameText: {
    width: '95%',
    color: '#898A8F',
    fontSize: width * 0.04,
    fontWeight: '400',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    marginLeft: 5,
  },
  docDTFWrapper: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#ECECEC',
  },
  dtfWrapper: {
    display: 'flex',
    flexDirection: 'column',
  },
  dtfmWrapper: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    borderRightWidth: 1,
    borderRightColor: '#ECECEC',
    marginRight: 10,
  },
  dtfText: {
    color: '#898A8F',
    fontSize: width * 0.045,
  },
  dtfSubText: {
    fontSize: width * 0.035,
    fontWeight: 'bold',
    paddingEnd: 15,
  },
  inputTextWrapper: {
    width: '100%',
    padding: 15,
  },
  inputStyle: {
    backgroundColor: '#F6F6F6',
    padding: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#D6D6D6',
    marginBottom: 15,
  },
  bookText: {
    width: '100%',
    textAlign: 'center',
    color: '#898A8F',
    fontSize: width * 0.035,
  },
  tcText: {
    color: '#3CB9C7',
  },
  bfbottomWrapper: {
    width: '95%',
    backgroundColor: '#fff',
    borderRadius: 40,
    padding: 20,
    elevation: 1,
    shadowColor: 'rgba(0, 0, 0, 0.25)',
    borderColor: '#C7C7C7',
    borderWidth: 1,
    position: 'absolute',
    bottom: 50,
    marginHorizontal: 12,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    height: height * 0.08,
  },
  feedbackTextbtn: {
    fontSize: width * 0.04,
    fontWeight: 'bold',
    marginLeft: 18,
  },
  bookTextbtnWrapper: {
    width: '70%',
    padding: 10,
    borderRadius: 40,
    marginLeft: 20,
    height: height * 0.08,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookTextbtn: {
    fontWeight: 'bold',
    fontSize: width * 0.05,
    textAlign: 'center',
  },
});
